### ISSUE TITLE
[FEATURE] Autocat log file on error

### ISSUE THREAD

**Issue by iCarossio** [LMaxence/gookme#10]
**Is your feature request related to a problem? Please describe.**
Frustration: having to cat manually the log file/

**Describe the solution you'd like**
Autocat the log file at the end of the execution when it fails!

**Comment by LMaxence** [comment]
Hello :)

Gookme will display the absolute file path of the file containing the error logs.

Specifically, if you run your commit hooks from vscode (or most terminals) you can simply ctrl+click on the displayed file path to open it. Would that be a sufficient option ?

**Comment by iCarossio** [comment]
💯 thanks

**Comment by rosaldo260** [comment]
`ctrl+click` doesn't work in all cases, for example GitKraken.
Would be great to make it configurable, so output can go to STDOUT.
